### ISSUE TITLE
CAN Decoder Bug

### ISSUE THREAD

**Issue by Vedanth15** [gcivil-nyu-org/fall2019-cs-gy-6063-team-moonsurvivors#255]
I tried using the CAN decoder and gave the CAN message given in the testing instructions. I didn't get any error nor decrypted the CAN. Not sure if the string was of wrong format or if it was right and the CAN decoder isn't working. Either ways I think user should know that if it was an error, an error message must be displayed saying that the format was wrong or something in similar manner. Otherwise as a user I might think that CAN decoder isn't working.

Once again, Im unsure if CAN decoder is working or not. I gave the CAN message from testing directions.

## Expected Behavior

An error message if the format of CAN message is incorrect.

## Current Behavior

No response from the page

## Steps to Reproduce

 
<img width="958" alt="CAN - mercury" src="https://user-images.githubusercontent.com/47909391/69662455-65d45b80-1052-11ea-8bf5-c98b8c644e9f.PNG">

Please look at the image above.

**Comment by de846** [comment]
Thanks for the comments and feedback. The "data" we provided in our testing documentation worked at one point, but then when I added stronger constraints on the data consistency, the code (rightfully) said that a bad request was being sent. We forgot to go back and verify that the data we provided was still valid, when it was no longer. I have since added more exceptions to the CAN message processing, including returning the data that was decoded so the user has a chance to examine it. This whole thing is basically to support demonstration because in the future, a hardware sensor is going to be transmitting  messages constructed from a protocol scheme that should reduce the likelihood of receiving garbage data (it will essentially be just identifying the sensor, the data length, and the actual data).  Some of my fixes were included in #266. 

The CAN Decoder UI is just for demonstration as well, but I fixed a bug there too that wasn't displaying the error response on the UI (so it does now). In addition, I also use Django's `JsonResponse` class to send all responses back with errors. In addition to adding more exception types and writing much more detailed tests that show what are examples of valid and invalid CAN messages, I also include the decoded data JSON back per your suggestion.
