### ISSUE TITLE
POST format unclear

### ISSUE THREAD

**Issue by ab7289** [gcivil-nyu-org/fall2019-cs-gy-6063-team-moonsurvivors#264]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Unclear what the format is to POST data to the API. 

## Expected Behavior
Documentation should either be made clear or the error response should return an indication of the valid POST body format.

## Current Behavior
POST api just returns generic invalid format message.

## Ideas for Improvement
Include a valid POST format descriptor in error message

## Steps to Reproduce

1. POST {"can": 9459720945368167357440}
2. POST {9459720945368167357440}
3. post {"can_id": 9459720945368167357440}

**Comment by de846** [comment]
Thanks for the comments. The "data" we provided in our testing documentation worked at one point, but then when I added stronger constraints on the data consistency, the code (rightfully) said that a bad request was being sent. We forgot to go back and verify that the data we provided was still valid, when it was no longer. I have since added more exceptions to the CAN message processing, including returning the data that was decoded so the user has a chance to examine it. This whole thing is basically to support demonstration because in the future, a hardware sensor is going to be transmitting  messages constructed from a protocol scheme that should reduce the likelihood of receiving garbage data (it will essentially be just identifying the sensor, the data length, and the actual data).  Some of my fixes were included in #266.
